### PR TITLE
Simple fox for (mid-Jun-2024) error

### PR DESCRIPTION
**Pull request by OsamaLab**
Added more headers for the web request to bypass the 403 forbidden error that Forvo started throwing around mid-Jun-2024

Fixes https://github.com/realmayus/anki_forvo_dl/issues/113

### CODE REVIEW

**Comment by OsamaLab** [comment]
Fixes https://github.com/realmayus/anki_forvo_dl/issues/113

**Comment by jarmanso7** [comment]
Thank you very much @OsamaLab. Since I heavily rely on this plugin for my studies, I am stuck until they merge this and release a new version of the plugin. Would you be kind to let me know how can I compile your branch and get a working version of the plugin in the meantime?

Best regards and thanks again.

**Comment by jarmanso7** [comment]
@OsamaLab I could figure it out. I posted the bundle [here](https://github.com/jarmanso7/anki_forvo_dl_hotfix_bundle/releases/download/hotfix/anki_forvo_dl.ankiaddon), just in case anyone else might be in the same shoes than me. Thank you again!

**Comment by Sylendmxo** [comment]
@OsamaLab Great work! I'm using an an old anki version with an old addon called migaku. The forvo here also stopped working. Any chance you could  work your magic on that too? I attached the forvo python file from migaku. Would be awesome if you could take a look. Thanks! 
[forvodl.zip](https://github.com/user-attachments/files/16507085/forvodl.zip)

**Comment by jarmanso7** [comment]
@Sylendmxo I have 0 Python knowledge, but based on @OsamaLab 's solution, which consists of adding additional headers to the HTTP request and the help of ChatGPT for formatting, I tried to update your script with such headers. Can you give it a try and see if it works?

[Github gist](https://gist.github.com/jarmanso7/f4cf4746326212cd580f64097d126ebb)

**Comment by Sylendmxo** [comment]
> @Sylendmxo I have 0 Python knowledge, but based on @OsamaLab 's solution, which consists of adding additional headers to the HTTP request and the help of ChatGPT for formatting, I tried to update your script with such headers. Can you give it a try and see if it works?
> 
> [Github gist](https://gist.github.com/jarmanso7/f4cf4746326212cd580f64097d126ebb) (see lines 100 to 106)

Thanks! I really appreciate the help. Unfortunately it did not work but resulted in a big error when starting anki. I also tried my luck with chatgpt but now I have a version where its not just showing "no results" for Forvo but goes into "loading" and then gives me a 403 error. Not sure if that is a good or a bad thing. :D

**Comment by realmayus** [comment]
Thank you!

**Pull request merged**
